version: "3.9"

services:
  weatherapi:
    build: .
    container_name: weather-api
    ports:
      - "8080:8080"
    environment:
      OpenWeather__ApiKey: ${OPENWEATHER_API_KEY}
    restart: unless-stopped
